### ISSUE TITLE
What are your most critical SCSS-Lint Linters?

### ISSUE THREAD

**Issue by Snugug** [Snugug/sass-lint#3]
We're looking to build a proof-of-concept Node based Sass linter. Please let us know what your [most wanted SCSS-Lint linters](https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md) for us to work on converting first.

**Comment by skyred** [comment]
I was wondering why you need a Node based? Because your editors are written in Node? Please enlighten.

**Comment by Snugug** [comment]
The three main reasons are speed (I find Node much much faster than Ruby), dependencies (Node based task runners are used pretty much everywhere, and not having a Ruby dependency for this would be a huge win with Libsass), and the want to have it fully pluggable.

**Comment by BPScott** [comment]
IMO the linters that most affect code style are the whitespace-related ones, so I'd start with those:

SpaceAfterComma
SpaceAfterPropertyColon
SpaceAfterPropertyName
SpaceBeforeBrace
SpaceBetweenParens

TrailingSemicolon

**Comment by xzyfer** [comment]
Also a couple reasons of my own:

As the vast majority of frontend tooling is already written in node. It seems weird to me that scss-lint wasn't originally written in node for this reason. However I can see potentially being able to leverage the existing Ruby based parser and a great incentive to do it in Ruby.

For many people, and many organisation, using languages which aren't already established (in that environment) can almost impossible to do. Since much of our existing frontend tool chains are in node, supporting it in our environments is a known cost. 
With the progress of Libsass in the last year many companies are migrating from Ruby sass to Libsass for performance improvements. In my team this meant no more ruby dependencies. The cost of supporting Ruby, and the headaches that comes with it (rvm, rbenv, bundler, rubygems as an addition point of failure) in our team is simply unjustifiable. I don't image we're alone in this.

**Comment by andrewliebchen** [comment]
We use linting mostly to maintain syntax similarities among authors, but of course it's also useful when it catches obvious mistakes. Here's a few that are particularly useful/get triggered a lot.

* EmptyRule
* IdSelector
* MergeableSelector
* NameFormat
* NestingDepth
* PlaceholderInExtend
* PropertySortOrder 
* SelectorDepth
* Shorthand

Looking forward to ditching our last Ruby dependency! :star2:

**Comment by onishiweb** [comment]
Firstly thanks for starting this up @Snugug we're looking at whether we can switch to LibSass/node-sass at some point in the near future, so this would be another nudge towards that direction and ditching our Ruby dependancies. 

Tend to agree with the folks above mainly re Linters, but here's a list of the ones I think have the most weight for us, we mostly at the moment use them for code style and help with refactoring (MergeableSelector has been invaluable).

- EmptyLineBetweenBlocks
- EmptyRule
- Indentation
- MergeableSelector
- PropertySpelling
- SingleLinePerProperty
- SingleLinePerSelector
- TrailingSemicolon

Cheers

**Comment by una** [comment]
YAY! This is the best! (SO necessary)

* PropertySortOrder
* TrailingSemicolon
* Indentation
* Shorthand
* LeadingZero
* SpaceAfterPropertyColon

:smiley:

**Comment by attiks** [comment]
We face the same problem of having to use ram only for scss-lint,  so :thumbsup:

**Comment by glenpike** [comment]
Been looking at this recently - for enforcing better standards in our coding.

++1 for whitespace related.

We've changed:

NameFormat
SelectorFormat

For BEM style naming.

**Comment by xzyfer** [comment]
I think we have enough for an initial milestone release. Thanks to everyone who commented.

```
EmptyLineBetweenBlocks
EmptyRule
FinalNewline
IdSelector
Indentation
LeadingZero
MergeableSelector
NameFormat
NestingDepth
PlaceholderInExtend
PropertySortOrder
PropertySpelling
SelectorDepth
Shorthand
SingleLinePerProperty
SingleLinePerSelector
SpaceAfterComma
SpaceAfterPropertyColon
SpaceAfterPropertyName
SpaceBeforeBrace
SpaceBetweenParens
TrailingSemicolon
```

**Comment by andrewliebchen** [comment]
Nice!
